### ISSUE TITLE
git tag sort 

### ISSUE THREAD

**Issue by hb0730** [gookit/gitw#31]
感觉通过`git tags --sort=-v:refname`进行获取两个tag不太精准

```git
$ git tag -l --sort=-v:refname
v1.0.0-beta
test-change-log/1.0.0
changelog/1.0.1-beta
2.0.1
2.0.0
1.0.0
```

```git
$ git describe --tags --abbrev=0
2.0.1
$ git describe --tags --abbrev=0 tags/2.0.1^
2.0.0
```

**Comment by inhere** [comment]
找了好几个方法，发现 `git tags --sort=-v:refname` 稍微好些. 

你是建议用 `git describe --tags` 来找吗

**Comment by hb0730** [comment]
> 找了好几个方法，发现 `git tags --sort=-v:refname` 稍微好些.
> 
> 你是建议用 `git describe --tags` 来找吗

`git tag --sort=-v:refname` 可能对同一类排序肯能更好

`git describe --tags --abbrev=0` 最新标记

**Comment by inhere** [comment]
👍 有啥可以改进的，欢迎提PR
